package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	httptransport "github.com/go-swagger/go-swagger/httpkit/client"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/arschles/swagger-test/client/todos"
)

// Default a to do list application HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new a to do list application HTTP client.
func NewHTTPClient(formats strfmt.Registry) *AToDoListApplication {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/", []string{"http"})
	return New(transport, formats)
}

// New creates a new a to do list application client
func New(transport client.Transport, formats strfmt.Registry) *AToDoListApplication {
	cli := new(AToDoListApplication)
	cli.Transport = transport

	cli.Todos = todos.New(transport, formats)

	return cli
}

// AToDoListApplication is a client for a to do list application
type AToDoListApplication struct {
	Todos *todos.Client

	Transport client.Transport
}

// SetTransport changes the transport on the client and all its subresources
func (c *AToDoListApplication) SetTransport(transport client.Transport) {
	c.Transport = transport

	c.Todos.SetTransport(transport)

}
